### ISSUE TITLE
obremap migrate

### ISSUE THREAD

**Issue by tasmidur** [moccacoders/node-obremap#120]
When run command  ```obremap migrate``` then,
```
Errores:  TypeError: DB.table is not a function
    at _callee2$ (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:168:23)
    at tryCatch (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:5:2255)
    at Generator._invoke (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:5:1815)
    at Generator.next (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:5:3106)
    at asyncGeneratorStep (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:13:103)
    at _next (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:15:194)
    at /home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:15:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:15:97)
    at Object.migrations (/home/user/.config/yarn/global/node_modules/@moccacoders/node-obremap/dist/cli/migrate/index.js:246:18)```

**Comment by raymundo-salazar** [comment]
work on it

**Comment by khalidJA** [comment]
> work on it

how far ?
